USE STUDB;
SELECT * FROM TTABLE;
SELECT * FROM BTABLE;
SELECT* FROM WTABLE;
-- WRITE A QUERY TO FETCH FIRST_NAME FROM WTABLE USING ALIAS NAME
SELECT FIRST_NAME AS WORKER_NAME FROM WTABLE;
-- WRITE A QUERY TO FIRST_NAME FROM WORKER TABLE IN UPPER CASE
SELECT FIRST_NAME,UPPER(FIRST_NAME) FROM WTABLE;
-- WRITE A QUERY TO FETCH UNIQUE VALUES OF DEPARTMENT  FROM WTABLE
SELECT DISTINCT(DEPARTMENT) FROM WTABLE;
-- WRITE A QUERY TO PRINT THE FIRST THREE CHARACTER OF FIRST_NAME FROM WTABLE
SELECT FIRST_NAME,LEFT(FIRST_NAME,3) FROM WTABLE;
-- WRITE A QUERY TO FIND POSITION OF THE ALPHABETS('A') IN THE FIRST NAME COLUMN 'Amitabh' FROM THE ETABLES
SELECT FIRST_NAME,POSITION('a' IN FIRST_NAME) FROM WTABLE WHERE FIRST_NAME="Amitabh";
-- WRITE A QUERY TO PRINT THE FIRST_NAME FROM THE WORKER TABLE AFTER REMOVING WHITE SPACES FROM THE RIGHT SIDE(6)
SELECT RTRIM("FIRST_NAME    ") FROM WTABLE;
-- WRITE A QUERY TO PRINT THE DEPARTMENT FROM WORKER TABLE AFTER REMOVING WHITE SPACE FROM LEFT SIDE(7)
SELECT LTRIM("    FIRST_NAME") FROM WTABLE;
-- WRITE A QUERY THAT FETCHES THE UNIQUE VALUES OF DEPARTMENT FROM THE WORKER TABLE AND PRINT ITS LENGTH(8)
SELECT DISTINCT DEPARTMENT,LENGTH(DEPARTMENT) FROM WTABLE;
-- WRITE A QUERY TO PRINT THE FIRST_NAME FROM THE WORKER TABLE AFTER REPLACING 'a' WITH 'A'(9)
SELECT FIRST_NAME,REPLACE(FIRST_NAME,"a","A") FROM WTABLE;
-- WRITE A QUERY TO PRINT THE FIRST_NAME AND LAST_NAME FROM THE WORKER TABLE INTO A SINGLE COLUMN COMPLETE_NAME.(10)
SELECT CONCAT(FIRST_NAME,"-",LAST_NAME) AS COMPLETE_NAME FROM WTABLE;
-- WRITE A QUERY TO PRINT ALL WORKER DETAILS FROM THE WORKER TABLE ORDER BY FIRST_NAME ASCENDING.(11)
SELECT * FROM WTABLE
ORDER BY FIRST_NAME ASC;
-- WRITE A QUERY TO PRINT ALL WORKER DETAILS FROM THE WTABLE ORDER BY FIRST_NAME ASCENDING AND DEPARTMENT(12)
SELECT * FROM WTABLE
ORDER BY FIRST_NAME ASC,DEPARTMENT DESC;
-- WRITE A QUERY TO PRINT DETAILS FOR WORKERS WITH THE FIRST NAMES "VIPUL" AND "SATISH" FROM THE WORKER TABLE(13)
SELECT * FROM WTABLE
WHERE FIRST_NAME="Vipul" OR FIRST_NAME="SATISH";
-- WRITE A QUERY TO PRINT DETAILS OF WORKERS EXCLUDING FIRST NAMES,'VIPUL','SATISH' FROM THE WORKER TABLE(14)     NOT ANS
SELECT * FROM WTABLE
WHERE FIRST_NAME!="Vipul" OR "Satish"; 
-- WRITE A QUERY TO PRINT DETAILS OF WORKERS WITH DEPARTMENT NAMES AS "ADMIN"(15)
SELECT  DEPARTMENT AS ADMIN FROM WTABLE;
-- WRITE A QUERY TO PRINT DETAILS OF THE WORKERS WHOSE FIRST_NAME CONTAINS 'a'(16)
SELECT * FROM WTABLE
WHERE FIRST_NAME LIKE "%a%";
-- WRITE A QUERY TO PRINT DETAILS OF THE WORKERS WHOSE FIRST_NAME END WITH 'a'(17)
SELECT * FROM WTABLE
WHERE FIRST_NAME LIKE "%a";
-- WRITE A QUERY TO PRINT DETAILS OF THE WORKER WHOSE FIRST_NAME END WITH 'H' AND CONTAINS SIX ALPHABETS(18)
SELECT * FROM WTABLE
WHERE FIRST_NAME LIKE "%h" ;
-- WRITE A QUERY TO PRINT DETAILS OF THE WORKERS WHOSE SALARY LIES BETWEEN 100000 AND 500000(19)
SELECT * FROM WTABLE
WHERE SALARY BETWEEN 100000 AND 500000;
-- WRITE A QUERY TO PRINT DETAILS OF THE WORKERS WHO JOINED IN FEB 2021(20)     
SELECT * FROM WTABLE
WHERE JOINING_DATE BETWEEN  "2021-01-20"  AND  "2021-02-20";
 -- WRITE A QUERY TO FETCH THE COUNT OF EMPLOYEES WORKING IN THE DEPARTMENT 'ADMIN'(21)
SELECT COUNT(*)  FROM WTABLE
WHERE    DEPARTMENT="Admin";
-- WRITE A QUERY TO FETCH WORKER NAMES WITH SALARIES>=50000 AND <=100000(22)
SELECT FIRST_NAME,SALARY FROM WTABLE
WHERE SALARY >=50000 AND SALARY <=100000;
-- WRITE A QUERY TO FETCH THE NUMBERS OF WORKER FOR EACH DEPARTMENT IN DESC ORDER.(23)
SELECT DEPARTMENT,COUNT(*) FROM WTABLE
GROUP BY DEPARTMENT;
-- WRITE A QUERY TO PRINT WORKER NAME WHO ARE MANAGERS.(24)




 